# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI-Linux

on:
  push:
    branches:
      - 'linux*'
      - '!master'
      - '!main'
  pull_request:
    branches:
      - 'linux*'
      - '!master'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      ## Setup
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev fd-find ripgrep
          alias fd='fdfind'
      - name: Install GENIE
        run: make update-genie-os

      ## Build and test (debug)
      - name: Build (debug)
        run: make build CONFIG=debug
      - name: Test (debug)
        run: bin/linux/argus-test
      
      ## Build and test (release)
      - name: Build (release)
        run: make build CONFIG=release
      - name: Test (release)
        run: bin/linux/argus-test
