# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI-Windows

on:
  push:
    branches:
      - 'win*'
      - '!master'
      - '!main'
  pull_request:
    branches:
      - 'win*'
      - '!master'
      - '!main'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      ## Setup
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install dependencies
        run: |
          vcpkg.exe install sdl2:x64-windows
          choco install fd ripgrep
      - name: Install GENIE
        run: make update-genie-os

      ## Build and test (debug)
      - name: Build (debug)
        run: make build CONFIG=debug
      - name: Test (debug)
        run: bin/windows/argus-test
      
      ## Build and test (release)
      - name: Build (release)
        run: make build CONFIG=release
      - name: Test (release)
        run: bin/windows/argus-test
